#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinitely
# Requirement: In between each iteration of the loops, add a sleep 2

while true
do
echo "To infinity and beyond"
sleep2
done
